require("laurynas.utils")
require("laurynas.g")
require("laurynas.options")

require("laurynas.colorscheme")
require("laurynas.dressing")
require("laurynas.gitsigns")
require("laurynas.filetypes")
require("laurynas.harpoon")
require("laurynas.mini")
require("laurynas.splits")
require("laurynas.comment")
require("laurynas.spectre")
require("laurynas.surround")

require("laurynas.lsp.style")
require("laurynas.lsp")
require("laurynas.cmp")

require("laurynas.copilot")
require("laurynas.indent-blankline")
require("laurynas.aerial")
require("laurynas.neotree")
require("laurynas.undotree")
require("laurynas.lualine")
require("laurynas.telescope")
require("laurynas.treesitter")
require("laurynas.keybinds")
require("laurynas.autocmds")
