#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m signal --add event=window_destroyed action="bash ./window-focus-on-destroy.sh"

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Tot$" manage=off
yabai -m rule --add app="^Music$" manage=off 
yabai -m rule --add app="^Doppler$" manage=off 
yabai -m rule --add app="^CleanShot X$" manage=off
yabai -m rule --add app="^Color Picker$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Around$" manage=off
yabai -m rule --add app="^Camo Studio$" manage=off
yabai -m rule --add app="^ImageOptim$" manage=off
yabai -m rule --add app="^The Unarchiver$" manage=off
yabai -m rule --add title='^Archive Utility$' manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Podcasts$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^DeepL$" manage=off
yabai -m rule --add app="^HighTop$" manage=off
yabai -m rule --add app="^ModKey$" manage=off
yabai -m rule --add app="^KeyLimePie$" manage=off
yabai -m rule --add app="^Detail$" manage=off
yabai -m rule --add app="^OBS Studio$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off 
yabai -m rule --add title="^Picture in Picture$" manage=off
yabai -m rule --add app="^Overcast$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off

yabai -m rule --add app="^Ivory$" space=^4
yabai -m rule --add app="^Signal$" space=^4
yabai -m rule --add app="^Telegram$" space=^4
yabai -m rule --add app="^WhatsApp -" space=^4
yabai -m rule --add app="^Messenger$" space=^4
yabai -m rule --add app="^Parcel$" manage=off
yabai -m rule --add app="^Octal$" space=^4
yabai -m rule --add app="^Messages$" space=^4
yabai -m rule --add app="^Digitakt$" manage=off
yabai -m rule --add app="^Hand Mirror$" manage=off
yabai -m rule --add app='^Mimestream$' space=^3
yabai -m rule --add app='^choose$' manage=off

yabai -m rule --add app="^iA Presenter$" title="^presentation - .{0,}" manage=off
yabai -m rule --add app='^Arc$' space=^2
yabai -m rule --add app='^Firefox Developer Edition$' space=^2
yabai -m rule --add app="^Arc$" title="^Laurynas$" manage=off
yabai -m rule --add app='^Slack$' space=^3
yabai -m rule --add app='^WezTerm$' space=^1
yabai -m rule --add app='^Code$' space=^1
yabai -m rule --add app='^Discord$' space=^4

echo "yabai configuration loaded.."

#END
